<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Category;
use App\Models\Decoration;
use App\Models\DecorationImage;
use App\Models\DecorationItem;
use App\Models\Addon;
use App\Models\Package;
use App\Models\ServiceArea;
use App\Models\Review;
use App\Models\GalleryItem;
use App\Models\Offer;
use App\Models\Faq;
use App\Models\SiteSetting;

class AdityaUtsavSeeder extends Seeder
{
    public function run()
    {
        // 1. Site Settings
        $settings = [
            ['key' => 'brand_name', 'value' => 'Aditya Utsav', 'type' => 'text'],
            ['key' => 'brand_tagline', 'value' => 'Traditional Bihar Wedding & Event Decorations', 'type' => 'text'],
            ['key' => 'primary_city', 'value' => 'Siwan', 'type' => 'text'],
            ['key' => 'primary_state', 'value' => 'Bihar', 'type' => 'text'],
            ['key' => 'contact_phone', 'value' => '+91 98765 43210', 'type' => 'text'],
            ['key' => 'contact_email', 'value' => 'contact@adityautsav.in', 'type' => 'text'],
            ['key' => 'contact_address', 'value' => 'Station Road, Near Babunia More, Siwan, Bihar - 841226', 'type' => 'text'],
            ['key' => 'announcement_text', 'value' => 'Wedding Season Bookings Open — Serving Siwan, Gopalganj, Chapra & Nearby Areas', 'type' => 'text'],
            ['key' => 'experience_years', 'value' => '12+', 'type' => 'text'],
            ['key' => 'weddings_completed', 'value' => '650+', 'type' => 'text'],
        ];

        foreach ($settings as $setting) {
            SiteSetting::updateOrCreate(['key' => $setting['key']], $setting);
        }

        // 2. Categories
        $categoriesData = [
            [
                'name' => 'Jaimala',
                'slug' => 'jaimala',
                'tagline' => 'Varmala & Stage Ceremony',
                'description' => 'Elegant floral and royal Jaimala stage decorations crafted for your sacred Varmala ritual.',
                'image_url' => 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
                'icon_name' => 'sparkles',
                'display_order' => 1,
                'is_featured' => true,
            ],
            [
                'name' => 'Wedding Mandap',
                'slug' => 'wedding-mandap',
                'tagline' => 'Sacred Vivah Pheras',
                'description' => 'Traditional and modern Mandap decoration designs for sacred Vedic rituals and Saat Phere.',
                'image_url' => 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=800&q=80',
                'icon_name' => 'fire',
                'display_order' => 2,
                'is_featured' => true,
            ],
            [
                'name' => 'Haldi',
                'slug' => 'haldi',
                'tagline' => 'Ubtan & Yellow Florals',
                'description' => 'Bright and vibrant Haldi ceremony setups with fresh marigold backdrops and traditional brass urlis.',
                'image_url' => 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
                'icon_name' => 'sun',
                'display_order' => 3,
                'is_featured' => true,
            ],
            [
                'name' => 'Mehendi',
                'slug' => 'mehendi',
                'tagline' => 'Henna & Festive Courtyard',
                'description' => 'Beautiful Mehendi seating and decoration setups with colorful drapes and floral jhula swings.',
                'image_url' => 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=800&q=80',
                'icon_name' => 'heart',
                'display_order' => 4,
                'is_featured' => true,
            ],
            [
                'name' => 'Sangeet',
                'slug' => 'sangeet',
                'tagline' => 'Musical & Lighting Night',
                'description' => 'Premium Sangeet stage and celebration decoration with dynamic lighting and acoustic setups.',
                'image_url' => 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=800&q=80',
                'icon_name' => 'music',
                'display_order' => 5,
                'is_featured' => true,
            ],
            [
                'name' => 'Reception',
                'slug' => 'reception',
                'tagline' => 'Grand Evening Stage',
                'description' => 'Elegant reception stage and venue decoration crafted to welcome family guests and dignitaries.',
                'image_url' => 'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=800&q=80',
                'icon_name' => 'trophy',
                'display_order' => 6,
                'is_featured' => true,
            ],
            [
                'name' => 'Tilak & Sagai',
                'slug' => 'tilak',
                'tagline' => 'Auspicious Ritual Setup',
                'description' => 'Traditional, dignified, and auspicious decoration for your family Tilak and Sagai ceremony.',
                'image_url' => 'https://images.unsplash.com/photo-1545232979-fbf6759c2560?auto=format&fit=crop&w=800&q=80',
                'icon_name' => 'award',
                'display_order' => 7,
                'is_featured' => false,
            ],
            [
                'name' => 'Baraat & Entrance',
                'slug' => 'baraat-entry',
                'tagline' => 'Royal Swagat & Gate',
                'description' => 'Grand welcoming gates, floral arches, and festive lighting for the groom and Baraat arrival.',
                'image_url' => 'https://images.unsplash.com/photo-1532712938310-34cb3982ef74?auto=format&fit=crop&w=800&q=80',
                'icon_name' => 'door-open',
                'display_order' => 8,
                'is_featured' => false,
            ],
        ];

        $categoryModels = [];
        foreach ($categoriesData as $catData) {
            $cat = Category::updateOrCreate(['slug' => $catData['slug']], $catData);
            $categoryModels[$catData['slug']] = $cat;
        }

        // 3. Add-ons
        $addonsData = [
            [
                'name' => 'Extra Fresh Floral Chandelier',
                'description' => 'Cascading fresh Rajnigandha, red rose petals, and marigold strings suspended over the stage.',
                'price' => 8000.00,
                'image' => 'https://images.unsplash.com/photo-1544078751-58fee2d8a03b?auto=format&fit=crop&w=600&q=80',
                'is_active' => true,
            ],
            [
                'name' => 'Heavy Floral Arch Welcome Gate',
                'description' => 'Grand 18ft entrance gateway decorated with fresh Genda Phool and red roses for Baraat swagat.',
                'price' => 15000.00,
                'image' => 'https://images.unsplash.com/photo-1532712938310-34cb3982ef74?auto=format&fit=crop&w=600&q=80',
                'is_active' => true,
            ],
            [
                'name' => 'Cold Pyro Sparkular Entry (4 Units)',
                'description' => 'Smokeless, non-hazardous golden cold fountain sparkular effects during bride/groom entry and Varmala.',
                'price' => 10000.00,
                'image' => 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=600&q=80',
                'is_active' => true,
            ],
            [
                'name' => 'Traditional Brass Urli & Diya Pathway',
                'description' => 'Set of 8 engraved brass urlis with floating marigold blossoms and oil lamps along the aisle.',
                'price' => 6500.00,
                'image' => 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80',
                'is_active' => true,
            ],
            [
                'name' => 'Royal Throne Loveseat Upgrade',
                'description' => 'Handcrafted gold-gilded high-back maharaja throne sofa with velvet upholstery.',
                'price' => 12000.00,
                'image' => 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=600&q=80',
                'is_active' => true,
            ],
            [
                'name' => 'Floral Swing (Jhula) for Mehendi/Photo Booth',
                'description' => 'Traditional wooden swing decorated with fresh marigold tassels and floral garlands.',
                'price' => 9000.00,
                'image' => 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=600&q=80',
                'is_active' => true,
            ],
            [
                'name' => 'VIP Family Lounge Seating (4 Diwans + 8 Bolsters)',
                'description' => 'Comfortable traditional diwan seating arrangement with silk covers for family elders.',
                'price' => 7500.00,
                'image' => 'https://images.unsplash.com/photo-1583939411023-14783179e581?auto=format&fit=crop&w=600&q=80',
                'is_active' => true,
            ],
        ];

        $addonModels = [];
        foreach ($addonsData as $ad) {
            $addon = Addon::updateOrCreate(['name' => $ad['name']], $ad);
            $addonModels[] = $addon;
        }

        // 4. Decorations (Comprehensive Catalog with >30 authentic setups)
        $decorationsData = [
            // ==================== 1. JAIMALA ====================
            [
                'category_slug' => 'jaimala',
                'name' => 'Traditional Bihar Jaimala Stage',
                'slug' => 'traditional-bihar-jaimala-stage',
                'tagline' => 'Grand floral stage with royal sofa seating and warm temple lighting',
                'short_description' => 'A quintessential Bihar wedding stage designed for the sacred Varmala ceremony with fresh red roses, golden pillars, and warm spotlighting.',
                'description' => 'A quintessential Bihar wedding stage designed for the sacred Varmala ceremony. Crafted with fresh red roses, white carnations, marigold garlands, handcrafted golden pillars, and warm spotlighting. Provides a regal backdrop for exchanging wedding garlands in front of family and guests.',
                'primary_image' => 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Siwan',
                'starting_price' => 75000,
                'base_price' => 75000.00,
                'discount_price' => 68000.00,
                'style' => 'Traditional',
                'primary_color' => 'Red & Gold',
                'color_theme' => 'Deep Burgundy & Warm Gold',
                'guest_capacity' => '200-500 Guests',
                'setup_time' => '4-6 Hours',
                'rating' => 4.9,
                'reviews_count' => 28,
                'is_featured' => true,
                'is_trending' => true,
                'is_available' => true,
                'is_active' => true,
                'features' => ['Fresh Red & White Roses', 'Royal High-Back Sofa', 'Traditional Golden Pillars', 'Warm Ambient Spotlights', 'Stage Carpet & Backdrop'],
                'items' => [
                    ['name' => '30ft Wide Red Rose & White Floral Backdrop', 'quantity' => 1],
                    ['name' => 'Royal High-Back Gold-Gilded Sofa', 'quantity' => 1],
                    ['name' => 'Handcrafted Golden Ornate Pillars', 'quantity' => 4],
                    ['name' => 'Warm LED Spot & Par Lighting Setup', 'quantity' => 8],
                    ['name' => 'Red Velvet Stage Carpet with Gold Trim', 'quantity' => 1],
                    ['name' => 'Floral Aisle Pillars with Brass Urlis', 'quantity' => 6],
                ],
                'display_order' => 1,
            ],
            [
                'category_slug' => 'jaimala',
                'name' => 'Mithila-Inspired Floral Stage',
                'slug' => 'mithila-inspired-floral-stage',
                'tagline' => 'Intricate cultural motifs combined with opulent fresh Rajnigandha florals',
                'short_description' => 'Inspired by the rich heritage of Mithila and North Indian art, featuring tasteful decorative frame work and cascading tuberoses.',
                'description' => 'Inspired by the rich heritage of Mithila and North Indian art, featuring tasteful decorative frame work, cascading tuberoses (Rajnigandha), and soft golden backdrops. Perfect for cultural Vivah celebrations.',
                'primary_image' => 'https://images.unsplash.com/photo-1583939411023-14783179e581?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Siwan',
                'starting_price' => 85000,
                'base_price' => 85000.00,
                'discount_price' => null,
                'style' => 'Royal',
                'primary_color' => 'Cream & Gold',
                'color_theme' => 'Cream, Gold & Red',
                'guest_capacity' => '500-1000 Guests',
                'setup_time' => '5-7 Hours',
                'rating' => 4.9,
                'reviews_count' => 21,
                'is_featured' => true,
                'is_trending' => false,
                'is_available' => true,
                'is_active' => true,
                'features' => ['Mithila Motif Panels', 'Fragrant Rajnigandha Strings', 'Bespoke Throne Seating', 'Crystal Chandelier Accents', 'Custom Photo Backdrop'],
                'items' => [
                    ['name' => 'Hand-Painted Mithila Decorative Panels', 'quantity' => 2],
                    ['name' => 'Cascading Fresh Rajnigandha Curtain', 'quantity' => 1],
                    ['name' => 'Maharaja Throne Pair in Velvet Upholstery', 'quantity' => 1],
                    ['name' => 'Warm Par Cans & Backlight Focus', 'quantity' => 10],
                    ['name' => 'Red & Cream Velvet Runway', 'quantity' => 1],
                ],
                'display_order' => 2,
            ],
            [
                'category_slug' => 'jaimala',
                'name' => 'Royal Red & Gold Jaimala Setup',
                'slug' => 'royal-red-gold-jaimala-setup',
                'tagline' => 'Opulent crimson velvet canopies with heavy Dutch rose arrangements',
                'short_description' => 'A royal grandeur Jaimala stage setup with crimson velvet drapery, heavy Dutch red rose arches, and crystal chandeliers.',
                'description' => 'An opulent red and gold stage setup designed for prestigious wedding celebrations. Includes rich velvet drapes, cascading fresh flower chandeliers, and regal royal sofas.',
                'primary_image' => 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Chapra / Saran',
                'starting_price' => 95000,
                'base_price' => 95000.00,
                'discount_price' => 88000.00,
                'style' => 'Luxury',
                'primary_color' => 'Red',
                'color_theme' => 'Crimson Red & Antique Gold',
                'guest_capacity' => '500-1000 Guests',
                'setup_time' => '6-8 Hours',
                'rating' => 5.0,
                'reviews_count' => 17,
                'is_featured' => true,
                'is_trending' => true,
                'is_available' => true,
                'is_active' => true,
                'features' => ['Heavy Dutch Rose Arch', 'Crystal Chandeliers', 'Crown Carved Sofa', 'Warm Wash Lighting', 'Aisle Carpeting'],
                'items' => [
                    ['name' => 'Massive Dutch Rose Archway Canopy', 'quantity' => 1],
                    ['name' => 'Antique Gold Carved Sovereign Couch', 'quantity' => 1],
                    ['name' => 'Hanging Crystal & Floral Chandeliers', 'quantity' => 3],
                    ['name' => 'Professional Stage Wash Lighting Kit', 'quantity' => 1],
                ],
                'display_order' => 3,
            ],
            [
                'category_slug' => 'jaimala',
                'name' => 'Classic Floral Jaimala Stage',
                'slug' => 'classic-floral-jaimala-stage',
                'tagline' => 'Elegant white carnations and pink rose backdrops with warm lighting',
                'short_description' => 'A timeless pastel floral stage setup featuring delicate roses, marigold accents, and graceful sofa seating.',
                'description' => 'A balanced and elegant floral stage combining classic Indian wedding aesthetics with subtle modern touches. Suitable for open-air lawns and marriage halls alike.',
                'primary_image' => 'https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Gopalganj',
                'starting_price' => 60000,
                'base_price' => 60000.00,
                'discount_price' => 55000.00,
                'style' => 'Floral',
                'primary_color' => 'Pink & White',
                'color_theme' => 'Soft Pink, White & Gold',
                'guest_capacity' => '200-500 Guests',
                'setup_time' => '4-5 Hours',
                'rating' => 4.8,
                'reviews_count' => 14,
                'is_featured' => false,
                'is_trending' => false,
                'is_available' => true,
                'is_active' => true,
                'features' => ['Pastel Floral Backdrop', 'Elegant Curved Couch', 'Fairy Light Drapes', 'Stage Riser Skirting'],
                'items' => [
                    ['name' => 'Pastel Floral Wall Frame with Roses', 'quantity' => 1],
                    ['name' => 'White & Gold Curved Loveseat', 'quantity' => 1],
                    ['name' => 'Side Floral Pillars with Marigolds', 'quantity' => 4],
                    ['name' => 'Fairy Light Drapes & Stage Wash', 'quantity' => 1],
                ],
                'display_order' => 4,
            ],

            // ==================== 2. WEDDING MANDAP ====================
            [
                'category_slug' => 'wedding-mandap',
                'name' => 'Classic Red & Gold Wedding Mandap',
                'slug' => 'classic-red-gold-wedding-mandap',
                'tagline' => 'Four-pillar sacred Vedic mandap adorned with fresh marigold and velvet drapes',
                'short_description' => 'The heart of traditional Vivah rituals. Constructed with sturdy 4-pillar Vedic architecture, rich crimson velvet drapes, and authentic Havan Kund space.',
                'description' => 'The heart of traditional Vivah rituals. Constructed with sturdy 4-pillar Vedic architecture, rich crimson velvet drapes, authentic havan kund space, and floral canopies for the sacred Saat Phere.',
                'primary_image' => 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Siwan',
                'starting_price' => 110000,
                'base_price' => 110000.00,
                'discount_price' => 99000.00,
                'style' => 'Traditional',
                'primary_color' => 'Red & Gold',
                'color_theme' => 'Royal Red & Pure Gold',
                'guest_capacity' => '200-500 Guests',
                'setup_time' => '6-8 Hours',
                'rating' => 5.0,
                'reviews_count' => 34,
                'is_featured' => true,
                'is_trending' => true,
                'is_available' => true,
                'is_active' => true,
                'features' => ['4-Pillar Vedic Mandap', 'Havan Kund Arrangement', 'Chauki & Low Seating with Cushions', 'Fresh Marigold Kalash', 'Auspicious Toran Entry'],
                'items' => [
                    ['name' => '4-Pillar Carved Wooden Mandap Frame (12x12ft)', 'quantity' => 1],
                    ['name' => 'Pure Brass Havan Kund with Fire Safety Base', 'quantity' => 1],
                    ['name' => 'Pooja Chauki Pair with Silk Seatings', 'quantity' => 4],
                    ['name' => 'Fresh Marigold & Rajnigandha Canopy Ceiling', 'quantity' => 1],
                    ['name' => 'Mango Leaf & Marigold Toran Entryway', 'quantity' => 1],
                ],
                'display_order' => 5,
            ],
            [
                'category_slug' => 'wedding-mandap',
                'name' => 'Marigold Floral Vedic Mandap',
                'slug' => 'marigold-floral-vedic-mandap',
                'tagline' => 'Auspicious yellow and orange Genda Phool strings with brass kalash pillars',
                'short_description' => 'A deeply auspicious and vibrant marigold floral mandap crafted for traditional North Indian Vivah rituals.',
                'description' => 'An authentic traditional setup celebrating the holy color of Haldi and Marigold. Features thousands of hand-strung local marigold blossoms, brass pots, and sacred havan seating.',
                'primary_image' => 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Mairwa',
                'starting_price' => 85000,
                'base_price' => 85000.00,
                'discount_price' => 78000.00,
                'style' => 'Floral',
                'primary_color' => 'Yellow & Orange',
                'color_theme' => 'Marigold Yellow, Orange & Gold',
                'guest_capacity' => '200-500 Guests',
                'setup_time' => '5-6 Hours',
                'rating' => 4.9,
                'reviews_count' => 22,
                'is_featured' => true,
                'is_trending' => false,
                'is_available' => true,
                'is_active' => true,
                'features' => ['10,000+ Fresh Marigold Blossoms', 'Brass Kalash Corner Posts', 'Traditional Chauki Mats', 'Havan Safety Shield'],
                'items' => [
                    ['name' => 'Marigold Strung 4-Pillar Mandap Structure', 'quantity' => 1],
                    ['name' => 'Copper Havan Kund with Base Support', 'quantity' => 1],
                    ['name' => 'Brass Kalash & Coconut Arrangements', 'quantity' => 4],
                    ['name' => 'Priest and Bride/Groom Chauki Set', 'quantity' => 1],
                ],
                'display_order' => 6,
            ],
            [
                'category_slug' => 'wedding-mandap',
                'name' => 'Royal Pavilion Vivah Mandap',
                'slug' => 'royal-pavilion-vivah-mandap',
                'tagline' => 'Grand hexagonal dome mandap with cascading Rajnigandha and chandelier',
                'short_description' => 'A magnificent multi-pillar wedding pavilion with cascading fragrant tuberoses, golden bells, and velvet carpets.',
                'description' => 'Built for large family celebrations and lawn weddings. This dome-structured mandap accommodates the entire family comfortably during the pheras.',
                'primary_image' => 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Chapra / Saran',
                'starting_price' => 135000,
                'base_price' => 135000.00,
                'discount_price' => null,
                'style' => 'Royal',
                'primary_color' => 'Gold & Maroon',
                'color_theme' => 'Antique Gold, Maroon & Amber',
                'guest_capacity' => '500-1000 Guests',
                'setup_time' => '7-9 Hours',
                'rating' => 5.0,
                'reviews_count' => 19,
                'is_featured' => true,
                'is_trending' => true,
                'is_available' => true,
                'is_active' => true,
                'features' => ['6-Pillar Domed Pavilion', 'Hanging Brass Ghungroos & Bells', 'Complete Family Floor Lounge', 'Warm LED Illumination'],
                'items' => [
                    ['name' => 'Hexagonal Heavy Domed Mandap Frame', 'quantity' => 1],
                    ['name' => 'Custom Havan Platform with Smoke Extractor', 'quantity' => 1],
                    ['name' => 'Embroidered Silk Chauki Set for Family', 'quantity' => 6],
                    ['name' => 'Complete Ambient Par & Halogen Lights', 'quantity' => 1],
                ],
                'display_order' => 7,
            ],
            [
                'category_slug' => 'wedding-mandap',
                'name' => 'Traditional Courtyard Mandap Setup',
                'slug' => 'traditional-courtyard-mandap-setup',
                'tagline' => 'Compact authentic mandap optimized for home courtyards and private lawns',
                'short_description' => 'A warm, intimate Vedic mandap design tailored specifically for family ancestral home courtyards and private gardens.',
                'description' => 'Designed specifically for traditional home courtyard weddings. Perfectly fitted to space dimensions while maintaining full ritual sanctity.',
                'primary_image' => 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Gopalganj',
                'starting_price' => 55000,
                'base_price' => 55000.00,
                'discount_price' => 50000.00,
                'style' => 'Classic',
                'primary_color' => 'Red & Yellow',
                'color_theme' => 'Red, Yellow & Green',
                'guest_capacity' => '50-200 Guests',
                'setup_time' => '3-4 Hours',
                'rating' => 4.8,
                'reviews_count' => 15,
                'is_featured' => false,
                'is_trending' => false,
                'is_available' => true,
                'is_active' => true,
                'features' => ['Compact 10x10ft Structure', 'Fresh Flower Garlands', 'Havan Space Setup', 'Quick On-Time Teardown'],
                'items' => [
                    ['name' => 'Adjustable 4-Pole Bamboo & Metal Mandap', 'quantity' => 1],
                    ['name' => 'Traditional Havan Kund Setup', 'quantity' => 1],
                    ['name' => 'Pooja Chauki & Asana Mats', 'quantity' => 4],
                ],
                'display_order' => 8,
            ],

            // ==================== 3. HALDI ====================
            [
                'category_slug' => 'haldi',
                'name' => 'Marigold Haldi Celebration Setup',
                'slug' => 'marigold-haldi-celebration-setup',
                'tagline' => 'Vibrant yellow and orange marigold floral curtains with traditional urlis',
                'short_description' => 'An energetic, sunlit decoration for the sacred Haldi ubtan ceremony including brass urli tub, marigold tassels, and yellow seating.',
                'description' => 'An energetic, sunlit outdoor or indoor decoration for the sacred Haldi ubtan ceremony. Includes brass urli tub for bride/groom, marigold tassels, matching yellow cushion seating.',
                'primary_image' => 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Mairwa',
                'starting_price' => 45000,
                'base_price' => 45000.00,
                'discount_price' => 40000.00,
                'style' => 'Traditional',
                'primary_color' => 'Yellow',
                'color_theme' => 'Sunlit Yellow & Marigold Orange',
                'guest_capacity' => '50-200 Guests',
                'setup_time' => '3-4 Hours',
                'rating' => 4.8,
                'reviews_count' => 19,
                'is_featured' => true,
                'is_trending' => true,
                'is_available' => true,
                'is_active' => true,
                'features' => ['Engraved Brass Urli', 'Fresh Genda Phool Garlands', 'Yellow Draped Cabana', 'Family Photo Booth Frame', 'Traditional Mud Pot Accents'],
                'items' => [
                    ['name' => 'Large Carved Brass Urli for Ubtan Ritual', 'quantity' => 1],
                    ['name' => 'Dense Yellow & Orange Marigold Wall (12x10ft)', 'quantity' => 1],
                    ['name' => 'Yellow Silk Cushions & Floor Gaddi Setup', 'quantity' => 6],
                    ['name' => 'Floral Hanging Tassels & Latkans', 'quantity' => 12],
                    ['name' => 'Haldi Photobooth Frame with Floral Border', 'quantity' => 1],
                ],
                'display_order' => 9,
            ],
            [
                'category_slug' => 'haldi',
                'name' => 'Royal Yellow Cabana Haldi Decor',
                'slug' => 'royal-yellow-cabana-haldi-decor',
                'tagline' => 'Canopy cabana decorated with fresh marigolds and brass lamps',
                'short_description' => 'A royal cabana tent with yellow flowing drapes, hanging floral bells, and decorated low chauki seating.',
                'description' => 'Transform your lawn or terrace into a lively Haldi celebration ground with flowing yellow drapes, brass urlis, and fresh floral jewelry corners.',
                'primary_image' => 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Siwan',
                'starting_price' => 52000,
                'base_price' => 52000.00,
                'discount_price' => null,
                'style' => 'Royal',
                'primary_color' => 'Yellow',
                'color_theme' => 'Yellow & Warm Gold',
                'guest_capacity' => '200-500 Guests',
                'setup_time' => '4-5 Hours',
                'rating' => 4.9,
                'reviews_count' => 16,
                'is_featured' => true,
                'is_trending' => false,
                'is_available' => true,
                'is_active' => true,
                'features' => ['4-Corner Yellow Silk Cabana', 'Grand Urli Tub with Petals', 'Brass Diyas on Stands', 'Custom Haldi Name Sign'],
                'items' => [
                    ['name' => 'Yellow Silk Draped Cabana Tent', 'quantity' => 1],
                    ['name' => 'Giant Brass Urli with Stool Support', 'quantity' => 1],
                    ['name' => 'Matching Floor Mattresses with Bolsters', 'quantity' => 4],
                    ['name' => 'Warm Fairy Lights and Spotlights', 'quantity' => 1],
                ],
                'display_order' => 10,
            ],
            [
                'category_slug' => 'haldi',
                'name' => 'Floral Haldi Courtyard Setup',
                'slug' => 'floral-haldi-courtyard-setup',
                'tagline' => 'Fresh sunflower, marigold, and banana leaf traditional arrangements',
                'short_description' => 'A nature-infused Haldi setup incorporating fresh banana leaves, sunflowers, and handcrafted clay pots.',
                'description' => 'Pure traditional elegance with natural elements including banana plant stems, earthen kalash, and radiant sunflower backdrops.',
                'primary_image' => 'https://images.unsplash.com/photo-1606216794074-735e91aa2c92?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Gorakhpur',
                'starting_price' => 48000,
                'base_price' => 48000.00,
                'discount_price' => 44000.00,
                'style' => 'Floral',
                'primary_color' => 'Yellow & Green',
                'color_theme' => 'Sunflower Yellow & Leaf Green',
                'guest_capacity' => '50-200 Guests',
                'setup_time' => '3-4 Hours',
                'rating' => 4.7,
                'reviews_count' => 12,
                'is_featured' => false,
                'is_trending' => true,
                'is_available' => true,
                'is_active' => true,
                'features' => ['Natural Banana Leaf Trusses', 'Sunflower Accents', 'Terracotta Mud Urli Options', 'Traditional Seating'],
                'items' => [
                    ['name' => 'Fresh Banana Plant Trusses & Torans', 'quantity' => 1],
                    ['name' => 'Sunflower & Marigold Backdrop Grid', 'quantity' => 1],
                    ['name' => 'Traditional Brass & Mud Urli Centerpiece', 'quantity' => 1],
                ],
                'display_order' => 11,
            ],

            // ==================== 4. MEHENDI ====================
            [
                'category_slug' => 'mehendi',
                'name' => 'Traditional Mehendi Courtyard Setup',
                'slug' => 'traditional-mehendi-courtyard-setup',
                'tagline' => 'Festive vibrant drapery with cozy low diwan seating and Rajasthani umbrellas',
                'short_description' => 'Designed for long, joyful afternoons of henna application featuring colorful drapery and comfortable floor mattresses.',
                'description' => 'Designed for long, joyful afternoons of henna application. Features colorful bohemian drapery, comfortable floor mattresses with bolsters, and folk decorative touches.',
                'primary_image' => 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Gopalganj',
                'starting_price' => 55000,
                'base_price' => 55000.00,
                'discount_price' => 49000.00,
                'style' => 'Colorful',
                'primary_color' => 'Teal & Magenta',
                'color_theme' => 'Teal, Magenta & Warm Amber',
                'guest_capacity' => '50-200 Guests',
                'setup_time' => '4-5 Hours',
                'rating' => 4.8,
                'reviews_count' => 16,
                'is_featured' => true,
                'is_trending' => false,
                'is_available' => true,
                'is_active' => true,
                'features' => ['Low Diwan Seating with Bolsters', 'Embroidered Umbrellas', 'Floral Swing (Jhula)', 'Fairy Light Drapes', 'Mehendi Artist Seating Station'],
                'items' => [
                    ['name' => 'Colorful Multi-Tone Silk Backdrop (15x10ft)', 'quantity' => 1],
                    ['name' => 'Embroidered Traditional Parasol Umbrellas', 'quantity' => 6],
                    ['name' => 'Comfortable Floor Mattresses with Bolster Cushions', 'quantity' => 6],
                    ['name' => 'Mehendi Artist Low Tables and Stools', 'quantity' => 3],
                    ['name' => 'Floral Hanging Tassels & Fairy String Lights', 'quantity' => 1],
                ],
                'display_order' => 12,
            ],
            [
                'category_slug' => 'mehendi',
                'name' => 'Royal Floral Jhula Mehendi Setup',
                'slug' => 'royal-floral-jhula-mehendi-setup',
                'tagline' => 'Handcrafted wooden swing enveloped in marigold, roses, and fairy lights',
                'short_description' => 'A standout Mehendi setup featuring a royal floral swing (Jhula), silk floor diwans, and customized photo corners.',
                'description' => 'The ultimate photogenic Mehendi setup. Centered around a gorgeous floral-draped wooden swing where the bride sits comfortably during her henna rituals.',
                'primary_image' => 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Siwan',
                'starting_price' => 65000,
                'base_price' => 65000.00,
                'discount_price' => null,
                'style' => 'Royal',
                'primary_color' => 'Pink & Amber',
                'color_theme' => 'Rose Pink, Amber & Gold',
                'guest_capacity' => '200-500 Guests',
                'setup_time' => '5-6 Hours',
                'rating' => 4.9,
                'reviews_count' => 24,
                'is_featured' => true,
                'is_trending' => true,
                'is_available' => true,
                'is_active' => true,
                'features' => ['Heavy Floral Wooden Swing', 'Photobooth Backdrop', 'Lounge Seating for Relatives', 'Fairy Light Ceiling Canopy'],
                'items' => [
                    ['name' => 'Solid Teakwood Swing Decorated with Roses & Marigolds', 'quantity' => 1],
                    ['name' => 'Floral Ceiling Canopy with Fairy Light Grid', 'quantity' => 1],
                    ['name' => 'Silk Floor Mattresses and Gaddi Sets', 'quantity' => 4],
                    ['name' => 'Mehendi Photo Prop Stand & Board', 'quantity' => 1],
                ],
                'display_order' => 13,
            ],
            [
                'category_slug' => 'mehendi',
                'name' => 'Vibrant Bohemian Mehendi Decor',
                'slug' => 'vibrant-bohemian-mehendi-decor',
                'tagline' => 'Tassel drapes, marigold torans, and vibrant floor cushions',
                'short_description' => 'A lively, colorful setup with multi-colored festive drapery, dreamcatcher motifs, and low chauki arrangements.',
                'description' => 'An energetic, youthful celebration setup combining North Indian cultural warmth with colorful bohemian patterns.',
                'primary_image' => 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Deoria',
                'starting_price' => 45000,
                'base_price' => 45000.00,
                'discount_price' => 40000.00,
                'style' => 'Colorful',
                'primary_color' => 'Multi-Color',
                'color_theme' => 'Multi-Color Fiesta',
                'guest_capacity' => '50-200 Guests',
                'setup_time' => '3-4 Hours',
                'rating' => 4.7,
                'reviews_count' => 11,
                'is_featured' => false,
                'is_trending' => false,
                'is_available' => true,
                'is_active' => true,
                'features' => ['Colorful Tassel Backdrop', 'Printed Floor Gaddi Sets', 'Flower Garland Accents', 'Ambient Lighting'],
                'items' => [
                    ['name' => 'Multi-Hue Drapery Backdrop', 'quantity' => 1],
                    ['name' => 'Low Diwan Set with Printed Covers', 'quantity' => 4],
                    ['name' => 'Handcrafted Torans and Bells', 'quantity' => 8],
                ],
                'display_order' => 14,
            ],

            // ==================== 5. SANGEET ====================
            [
                'category_slug' => 'sangeet',
                'name' => 'Elegant Sangeet & Musical Stage',
                'slug' => 'elegant-sangeet-musical-stage',
                'tagline' => 'Dynamic ambient lighting, LED backdrop structures, and glossy dance floor',
                'short_description' => 'High-voltage stage for family performances and musical celebrations with synchronized warm lighting.',
                'description' => 'High-voltage stage for family performances and musical celebrations. Equipped with synchronized warm stage lighting, acoustic backdrops, and family lounge seating.',
                'primary_image' => 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Siwan',
                'starting_price' => 90000,
                'base_price' => 90000.00,
                'discount_price' => 82000.00,
                'style' => 'Modern',
                'primary_color' => 'Burgundy & Gold',
                'color_theme' => 'Burgundy, Amber & Gold',
                'guest_capacity' => '500-1000 Guests',
                'setup_time' => '5-7 Hours',
                'rating' => 4.8,
                'reviews_count' => 15,
                'is_featured' => false,
                'is_trending' => true,
                'is_available' => true,
                'is_active' => true,
                'features' => ['Wooden Performance Stage', 'Warm Par Lighting', 'Family Lounge Couches', 'Dholak & Acoustic Corner', 'Sparkular Safe Pyro Setup'],
                'items' => [
                    ['name' => '24x16ft Heavy Wooden Performance Stage with Carpet', 'quantity' => 1],
                    ['name' => 'Acoustic Floral Truss Backdrop with LED Bars', 'quantity' => 1],
                    ['name' => 'Intelligent Moving Par & Beam Lighting Kit', 'quantity' => 12],
                    ['name' => 'Dholak & Traditional Singer Chauki Platform', 'quantity' => 1],
                    ['name' => 'VIP Family Sofa Lounge (4 Couches + Tables)', 'quantity' => 1],
                ],
                'display_order' => 15,
            ],
            [
                'category_slug' => 'sangeet',
                'name' => 'Royal Amber Sangeet Celebration',
                'slug' => 'royal-amber-sangeet-celebration',
                'tagline' => 'Warm candle-glow lighting effects, floral trusses, and plush sofa seating',
                'short_description' => 'A royal musical night setup featuring warm golden wash lighting, acoustic drapes, and traditional dholak stages.',
                'description' => 'Combines traditional North Indian festive warmth with modern stage presentation for a memorable musical night for the entire extended family.',
                'primary_image' => 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Chapra / Saran',
                'starting_price' => 115000,
                'base_price' => 115000.00,
                'discount_price' => null,
                'style' => 'Royal',
                'primary_color' => 'Amber & Gold',
                'color_theme' => 'Amber, Gold & Deep Red',
                'guest_capacity' => '500-1000 Guests',
                'setup_time' => '6-8 Hours',
                'rating' => 4.9,
                'reviews_count' => 18,
                'is_featured' => true,
                'is_trending' => true,
                'is_available' => true,
                'is_active' => true,
                'features' => ['Tiered Performance Stage', 'Warm Golden Lighting Grid', 'VIP Family Sofas', 'Traditional Diya Trusses'],
                'items' => [
                    ['name' => 'Tiered Performance Wooden Platform', 'quantity' => 1],
                    ['name' => 'Golden Laser-Cut Frame Backdrop with Florals', 'quantity' => 1],
                    ['name' => 'Synchronized Ambient Par Lights', 'quantity' => 16],
                    ['name' => 'Family Lounge Couches and Low Tables', 'quantity' => 6],
                ],
                'display_order' => 16,
            ],

            // ==================== 6. RECEPTION ====================
            [
                'category_slug' => 'reception',
                'name' => 'Grand Reception Stage',
                'slug' => 'grand-reception-stage',
                'tagline' => 'Opulent wide floral backdrop with golden geometric frames and warm lighting',
                'short_description' => 'A breathtaking stage designed for welcoming hundreds of family guests and dignitaries with pristine florals.',
                'description' => 'A breathtaking stage designed for welcoming hundreds of family guests and dignitaries. Spacious, regal, with pristine white and royal burgundy floral compositions.',
                'primary_image' => 'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Chapra / Saran',
                'starting_price' => 125000,
                'base_price' => 125000.00,
                'discount_price' => 110000.00,
                'style' => 'Luxury',
                'primary_color' => 'Royal Rose',
                'color_theme' => 'Royal Rose, Cream & Gold',
                'guest_capacity' => '1000+ Guests',
                'setup_time' => '6-8 Hours',
                'rating' => 4.9,
                'reviews_count' => 32,
                'is_featured' => true,
                'is_trending' => true,
                'is_available' => true,
                'is_active' => true,
                'features' => ['30ft Panoramic Floral Wall', 'Crown Carved Loveseat', 'Golden Geometric Truss', 'Warm Stage Wash Lighting', 'Red Carpet Pathway'],
                'items' => [
                    ['name' => '30x12ft Grand Panoramic Fresh Flower Wall', 'quantity' => 1],
                    ['name' => 'Handcrafted Sovereign Crown Loveseat', 'quantity' => 1],
                    ['name' => 'Golden Geometric Truss Frames with Crystal Accents', 'quantity' => 4],
                    ['name' => 'High-Lumen Stage Wash Lighting Setup', 'quantity' => 12],
                    ['name' => '50ft Red Carpet Guest Welcome Runway', 'quantity' => 1],
                ],
                'display_order' => 17,
            ],
            [
                'category_slug' => 'reception',
                'name' => 'Royal Velvet Reception Setup',
                'slug' => 'royal-velvet-reception-setup',
                'tagline' => 'Burgundy velvet drapery with white floral cascade and gold throne',
                'short_description' => 'An aristocratic reception stage featuring deep burgundy velvet drapery, white orchids, and gold chandeliers.',
                'description' => 'Crafted for formal wedding receptions with a grand imperial visual appeal. Features heavy velvet drapes, floral chandeliers, and throne seating.',
                'primary_image' => 'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Siwan',
                'starting_price' => 140000,
                'base_price' => 140000.00,
                'discount_price' => null,
                'style' => 'Royal',
                'primary_color' => 'Burgundy',
                'color_theme' => 'Deep Burgundy & Pure Gold',
                'guest_capacity' => '1000+ Guests',
                'setup_time' => '7-9 Hours',
                'rating' => 5.0,
                'reviews_count' => 27,
                'is_featured' => true,
                'is_trending' => false,
                'is_available' => true,
                'is_active' => true,
                'features' => ['Deep Burgundy Velvet Drapes', 'White Orchid Floral Cascades', 'Maharaja Throne Pair', 'Full Stage Spotlights'],
                'items' => [
                    ['name' => 'Velvet Pleated Backdrop with Gold Trims', 'quantity' => 1],
                    ['name' => 'Double Maharaja Throne Chair Set', 'quantity' => 1],
                    ['name' => 'Crystal and Fresh Floral Hanging Fixtures', 'quantity' => 4],
                    ['name' => 'Warm Focus Follow Spot & Par System', 'quantity' => 1],
                ],
                'display_order' => 18,
            ],
            [
                'category_slug' => 'reception',
                'name' => 'Classic Elegance Reception Stage',
                'slug' => 'classic-elegance-reception-stage',
                'tagline' => 'Subtle cream and blush floral arches with warm ambient spotlights',
                'short_description' => 'A refined and balanced reception stage designed for family banquet halls and lawn receptions.',
                'description' => 'Clean lines, fresh pastel florals, and timeless sofa seating designed to highlight the couple in photos while keeping stage mobility easy for family elders.',
                'primary_image' => 'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Gorakhpur',
                'starting_price' => 95000,
                'base_price' => 95000.00,
                'discount_price' => 88000.00,
                'style' => 'Classic',
                'primary_color' => 'Cream',
                'color_theme' => 'Cream, Gold & Soft Amber',
                'guest_capacity' => '500-1000 Guests',
                'setup_time' => '5-6 Hours',
                'rating' => 4.8,
                'reviews_count' => 19,
                'is_featured' => false,
                'is_trending' => false,
                'is_available' => true,
                'is_active' => true,
                'features' => ['Cream Silk Drapes', 'Fresh Flower Arches', 'Curved Sofa Loveseat', 'Stage Wash Lighting'],
                'items' => [
                    ['name' => 'Cream Silk Pleated Wall with Floral Arches', 'quantity' => 1],
                    ['name' => 'Curved Gold-Rimmed Upholstered Sofa', 'quantity' => 1],
                    ['name' => 'Side Floral Urli Stands', 'quantity' => 4],
                ],
                'display_order' => 19,
            ],

            // ==================== 7. TILAK & BARAAT ====================
            [
                'category_slug' => 'tilak',
                'name' => 'Traditional Auspicious Tilak Setup',
                'slug' => 'traditional-auspicious-tilak-setup',
                'tagline' => 'Dignified ritual stage with brass lamps, auspicious chauki, and marigold torans',
                'short_description' => 'A traditional and respectful setup for the auspicious Tilak and Sagai ceremony honoring family elders.',
                'description' => 'Crafted specifically for the Tilak ceremony where rituals, respect, and family dignity are paramount. Features authentic pooja chaukis, brass diyas, and mango leaf torans.',
                'primary_image' => 'https://images.unsplash.com/photo-1545232979-fbf6759c2560?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Siwan',
                'starting_price' => 45000,
                'base_price' => 45000.00,
                'discount_price' => 38000.00,
                'style' => 'Traditional',
                'primary_color' => 'Red & Gold',
                'color_theme' => 'Sacred Red, Yellow & Gold',
                'guest_capacity' => '50-200 Guests',
                'setup_time' => '3-4 Hours',
                'rating' => 4.8,
                'reviews_count' => 14,
                'is_featured' => false,
                'is_trending' => false,
                'is_available' => true,
                'is_active' => true,
                'features' => ['Pooja Chauki Arrangement', 'Brass Kalash & Deepstambh', 'Traditional Toran Backdrop', 'Family Seating'],
                'items' => [
                    ['name' => 'Handcrafted Tilak Pooja Chauki Pair', 'quantity' => 1],
                    ['name' => 'Brass Deepstambh Pair with Oil Lamps', 'quantity' => 2],
                    ['name' => 'Marigold and Mango Leaf Backwall', 'quantity' => 1],
                    ['name' => 'Family Elder Low Seating Mattress Sets', 'quantity' => 4],
                ],
                'display_order' => 20,
            ],
            [
                'category_slug' => 'baraat-entry',
                'name' => 'Royal Baraat Swagat Gate',
                'slug' => 'royal-baraat-swagat-gate',
                'tagline' => 'Majestic floral arched gateway with traditional brass lamps and shahnai stage',
                'short_description' => 'The grand entrance where the groom and his wedding procession are warmly greeted with royal Swagat.',
                'description' => 'The grand entrance where the groom and his wedding procession are warmly greeted with royal Swagat. Features marigold arches, brass diyas, and grand toran arches.',
                'primary_image' => 'https://images.unsplash.com/photo-1532712938310-34cb3982ef74?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Siwan',
                'starting_price' => 40000,
                'base_price' => 40000.00,
                'discount_price' => 35000.00,
                'style' => 'Royal',
                'primary_color' => 'Yellow & Red',
                'color_theme' => 'Marigold Yellow & Royal Red',
                'guest_capacity' => '500-1000 Guests',
                'setup_time' => '4-5 Hours',
                'rating' => 4.7,
                'reviews_count' => 18,
                'is_featured' => false,
                'is_trending' => false,
                'is_available' => true,
                'is_active' => true,
                'features' => ['Grand 20ft Archway', 'Hanging Brass Diyas', 'Shehnai Artist Platform', 'Red Velvet Carpet Entry', 'Flower Shower Points'],
                'items' => [
                    ['name' => '20ft Heavy Archway with Fresh Marigold & Red Roses', 'quantity' => 1],
                    ['name' => 'Hanging Brass Diyas and Lamps', 'quantity' => 10],
                    ['name' => 'Elevated Shehnai Artist Platform (8x6ft)', 'quantity' => 1],
                    ['name' => 'Red Velvet Entry Carpet Runner', 'quantity' => 1],
                ],
                'display_order' => 21,
            ],

            // Additional Category Enrichments
            [
                'category_slug' => 'jaimala',
                'name' => 'Royal Marigold Jaimala Stage',
                'slug' => 'royal-marigold-jaimala-stage',
                'tagline' => 'Golden yellow marigold tiers and red rose arches for royal Varmala',
                'short_description' => 'A royal Varmala stage with multi-tiered yellow marigold pillars and carved gold throne seating.',
                'description' => 'A majestic stage featuring thousands of fresh marigold flowers arranged in royal tiers with ambient lighting and brass urli aisle pillars.',
                'primary_image' => 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Siwan',
                'starting_price' => 70000,
                'base_price' => 70000.00,
                'discount_price' => 64000.00,
                'style' => 'Royal',
                'primary_color' => 'Yellow & Red',
                'color_theme' => 'Golden Marigold & Royal Red',
                'guest_capacity' => '200-500 Guests',
                'setup_time' => '4-5 Hours',
                'rating' => 4.9,
                'reviews_count' => 23,
                'is_featured' => true,
                'is_trending' => true,
                'is_available' => true,
                'is_active' => true,
                'features' => ['Multi-Tiered Marigold Pillars', 'Carved Sovereign Chairs', 'Brass Urli Pathway', 'Stage Carpet'],
                'items' => [
                    ['name' => 'Multi-Tiered Fresh Marigold Frame (24ft)', 'quantity' => 1],
                    ['name' => 'Carved Sovereign Chair Pair', 'quantity' => 1],
                    ['name' => 'Aisle Urlis with Floating Diyas', 'quantity' => 6],
                ],
                'display_order' => 22,
            ],
            [
                'category_slug' => 'wedding-mandap',
                'name' => 'Royal Domed Heritage Mandap',
                'slug' => 'royal-domed-heritage-mandap',
                'tagline' => 'Imperial octagonal dome mandap with carved gold pillars and floral bells',
                'short_description' => 'An imperial wedding mandap with handcrafted domed ceiling, golden bells, and sacred Vedic Havan platform.',
                'description' => 'Designed for unforgettable Vivah ceremonies with authentic architectural sanctity, fresh Rajnigandha hangings, and luxurious family floor seating.',
                'primary_image' => 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Chapra / Saran',
                'starting_price' => 120000,
                'base_price' => 120000.00,
                'discount_price' => 108000.00,
                'style' => 'Royal',
                'primary_color' => 'Gold & Maroon',
                'color_theme' => 'Imperial Gold & Maroon',
                'guest_capacity' => '500-1000 Guests',
                'setup_time' => '7-9 Hours',
                'rating' => 5.0,
                'reviews_count' => 29,
                'is_featured' => true,
                'is_trending' => false,
                'is_available' => true,
                'is_active' => true,
                'features' => ['Octagonal Gold Dome Frame', 'Brass Pooja Kalash Set', 'Heavy Rajnigandha Canopy', 'Vedic Havan Kund'],
                'items' => [
                    ['name' => 'Octagonal Domed Mandap Frame Structure', 'quantity' => 1],
                    ['name' => 'Pure Brass Havan Kund with Hearth', 'quantity' => 1],
                    ['name' => 'Embroidered Silk Floor Gaddi Set', 'quantity' => 8],
                ],
                'display_order' => 23,
            ],
            [
                'category_slug' => 'haldi',
                'name' => 'Traditional Bihar Courtyard Haldi',
                'slug' => 'traditional-bihar-courtyard-haldi',
                'tagline' => 'Authentic home courtyard setup with brass urli, genda phool, and clay pots',
                'short_description' => 'A joyful family Haldi setup tailored for courtyard gatherings with traditional marigold hangings.',
                'description' => 'Brings back the soulful warmth of ancestral village celebrations with handwoven mats, fresh marigold torans, and a grand brass urli for the bride and groom.',
                'primary_image' => 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Mairwa',
                'starting_price' => 38000,
                'base_price' => 38000.00,
                'discount_price' => 34000.00,
                'style' => 'Traditional',
                'primary_color' => 'Yellow',
                'color_theme' => 'Yellow & Orange',
                'guest_capacity' => '50-200 Guests',
                'setup_time' => '3-4 Hours',
                'rating' => 4.8,
                'reviews_count' => 17,
                'is_featured' => false,
                'is_trending' => true,
                'is_available' => true,
                'is_active' => true,
                'features' => ['Hand-carved Brass Urli', 'Yellow Marigold Torans', 'Low Wooden Chauki', 'Clay Pot Decor'],
                'items' => [
                    ['name' => 'Brass Urli Bowl with Stool', 'quantity' => 1],
                    ['name' => 'Fresh Marigold Drapery Wall (10x8ft)', 'quantity' => 1],
                    ['name' => 'Traditional Chauki with Silk Mat', 'quantity' => 2],
                ],
                'display_order' => 24,
            ],
            [
                'category_slug' => 'haldi',
                'name' => 'Royal Haldi Setup with Urli',
                'slug' => 'royal-haldi-setup-with-urli',
                'tagline' => 'Canopy of marigold bells with giant brass urli and royal cushions',
                'short_description' => 'A regal Haldi setup featuring a 4ft brass urli, cascading marigold bells, and vibrant photobooth.',
                'description' => 'Crafted for energetic Haldi ceremonies with high-volume photo moments. Features heavy marigold bell clusters, yellow silk carpets, and flower shower basket stations.',
                'primary_image' => 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Siwan',
                'starting_price' => 50000,
                'base_price' => 50000.00,
                'discount_price' => 45000.00,
                'style' => 'Royal',
                'primary_color' => 'Yellow',
                'color_theme' => 'Vibrant Yellow & Gold',
                'guest_capacity' => '200-500 Guests',
                'setup_time' => '4-5 Hours',
                'rating' => 4.9,
                'reviews_count' => 25,
                'is_featured' => true,
                'is_trending' => true,
                'is_available' => true,
                'is_active' => true,
                'features' => ['4ft Engraved Urli', 'Marigold Bell Hangings', 'Haldi Photo Frame', 'Silk Cushion Floor Sets'],
                'items' => [
                    ['name' => 'Giant Brass Urli on Carved Base', 'quantity' => 1],
                    ['name' => 'Marigold Bell Clusters (20 units)', 'quantity' => 1],
                    ['name' => 'Yellow Silk Floor Lounge (6 cushions)', 'quantity' => 1],
                ],
                'display_order' => 25,
            ],
            [
                'category_slug' => 'mehendi',
                'name' => 'Floral Mehendi Canopy Decor',
                'slug' => 'floral-mehendi-canopy-decor',
                'tagline' => 'Delicate pink and orange drapery canopy with floral swing and lanterns',
                'short_description' => 'An enchanting floral canopy for daytime Mehendi celebrations with swinging jhula and tea tables.',
                'description' => 'Features delicate floral ropes, embroidered Rajasthani umbrellas, and comfortable diwan seating for family members applying Mehendi.',
                'primary_image' => 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Chapra / Saran',
                'starting_price' => 58000,
                'base_price' => 58000.00,
                'discount_price' => 52000.00,
                'style' => 'Floral',
                'primary_color' => 'Pink & White',
                'color_theme' => 'Pastel Pink & Tangerine',
                'guest_capacity' => '50-200 Guests',
                'setup_time' => '4-5 Hours',
                'rating' => 4.8,
                'reviews_count' => 14,
                'is_featured' => false,
                'is_trending' => true,
                'is_available' => true,
                'is_active' => true,
                'features' => ['Floral Draped Canopy', 'Suspended Teakwood Jhula', 'Artist Low Seating', 'Parasol Accents'],
                'items' => [
                    ['name' => 'Floral Canopy Frame with Silk Ropes', 'quantity' => 1],
                    ['name' => 'Suspended Teakwood Jhula with Flower Garlands', 'quantity' => 1],
                    ['name' => 'Embroidered Parasols and Stools', 'quantity' => 4],
                ],
                'display_order' => 26,
            ],
            [
                'category_slug' => 'mehendi',
                'name' => 'Traditional Mehendi Diwan Setup',
                'slug' => 'traditional-mehendi-diwan-setup',
                'tagline' => 'Warm festive floor diwans with colorful bolsters and marigold backdrop',
                'short_description' => 'Cozy traditional diwan seating with festive backdrops and comfortable henna stations.',
                'description' => 'A relaxed and vibrant Mehendi lounge setup perfect for family courtyards and banquet halls.',
                'primary_image' => 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Gorakhpur',
                'starting_price' => 42000,
                'base_price' => 42000.00,
                'discount_price' => 38000.00,
                'style' => 'Colorful',
                'primary_color' => 'Multi-Color',
                'color_theme' => 'Teal, Mustard & Crimson',
                'guest_capacity' => '50-200 Guests',
                'setup_time' => '3-4 Hours',
                'rating' => 4.7,
                'reviews_count' => 13,
                'is_featured' => false,
                'is_trending' => false,
                'is_available' => true,
                'is_active' => true,
                'features' => ['Low Floor Diwans', 'Colorful Silk Bolsters', 'Marigold Curtain Backdrop', 'Henna Artist Stands'],
                'items' => [
                    ['name' => 'Low Diwan Set with Silk Covers', 'quantity' => 4],
                    ['name' => 'Marigold and Tassel Curtain (12ft)', 'quantity' => 1],
                    ['name' => 'Mehendi Artist Stools with Trays', 'quantity' => 2],
                ],
                'display_order' => 27,
            ],
            [
                'category_slug' => 'sangeet',
                'name' => 'Royal Sangeet Musical Night Stage',
                'slug' => 'royal-sangeet-musical-night-stage',
                'tagline' => 'Grand musical performance stage with acoustic truss and golden illumination',
                'short_description' => 'A royal stage built for joyous Sangeet family dance performances and musical nights.',
                'description' => 'Equipped with heavy timber staging, warm moving par lighting, crystal chandeliers, and front VIP family sofas.',
                'primary_image' => 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Siwan',
                'starting_price' => 105000,
                'base_price' => 105000.00,
                'discount_price' => 95000.00,
                'style' => 'Royal',
                'primary_color' => 'Amber & Gold',
                'color_theme' => 'Amber Glow & Royal Gold',
                'guest_capacity' => '500-1000 Guests',
                'setup_time' => '6-8 Hours',
                'rating' => 4.9,
                'reviews_count' => 21,
                'is_featured' => true,
                'is_trending' => true,
                'is_available' => true,
                'is_active' => true,
                'features' => ['Heavy Timber Dance Stage', 'Synchronized Beam Lights', 'VIP Leatherette Sofas', 'Cold Spark Machine Ready'],
                'items' => [
                    ['name' => '28x18ft Reinforced Performance Stage with Carpet', 'quantity' => 1],
                    ['name' => 'Acoustic Floral Truss with Amber Par Cans', 'quantity' => 1],
                    ['name' => 'VIP Family Sofa Lounge Set', 'quantity' => 1],
                ],
                'display_order' => 28,
            ],
            [
                'category_slug' => 'sangeet',
                'name' => 'Dynamic LED Sangeet Celebration',
                'slug' => 'dynamic-led-sangeet-celebration',
                'tagline' => 'High-energy musical stage with LED visual walls and rhythmic wash lights',
                'short_description' => 'A modern high-energy stage setup featuring high-resolution LED backdrop screens and dance lighting.',
                'description' => 'Tailored for lively family choreographies, DJ setups, and traditional North Indian Dholak performances.',
                'primary_image' => 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Chapra / Saran',
                'starting_price' => 125000,
                'base_price' => 125000.00,
                'discount_price' => null,
                'style' => 'Modern',
                'primary_color' => 'Teal & Magenta',
                'color_theme' => 'Neon Glow & Royal Purple',
                'guest_capacity' => '500-1000 Guests',
                'setup_time' => '6-8 Hours',
                'rating' => 5.0,
                'reviews_count' => 26,
                'is_featured' => true,
                'is_trending' => true,
                'is_available' => true,
                'is_active' => true,
                'features' => ['P3 LED Video Backdrop Wall', 'Moving Head Intelligent Lights', 'Stage Riser Steps', 'Sound Support Rigging'],
                'items' => [
                    ['name' => 'P3 High-Res LED Screen (16x10ft)', 'quantity' => 1],
                    ['name' => 'Moving Head Beam Lights Rigging', 'quantity' => 8],
                    ['name' => 'Dance Stage with Glossy Flooring', 'quantity' => 1],
                ],
                'display_order' => 29,
            ],
            [
                'category_slug' => 'reception',
                'name' => 'Grand Bihar Reception Stage',
                'slug' => 'grand-bihar-reception-stage',
                'tagline' => 'Massive 35ft royal floral wall with golden carved arches and throne',
                'short_description' => 'An opulent reception stage with 35ft fresh rose backdrop, gold arches, and royal throne seating.',
                'description' => 'The crown jewel of wedding reception setups. Designed for grand welcoming ceremonies with family and prominent guests.',
                'primary_image' => 'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Siwan',
                'starting_price' => 135000,
                'base_price' => 135000.00,
                'discount_price' => 120000.00,
                'style' => 'Luxury',
                'primary_color' => 'Burgundy & Gold',
                'color_theme' => 'Burgundy, Ivory & Imperial Gold',
                'guest_capacity' => '1000+ Guests',
                'setup_time' => '7-9 Hours',
                'rating' => 5.0,
                'reviews_count' => 38,
                'is_featured' => true,
                'is_trending' => true,
                'is_available' => true,
                'is_active' => true,
                'features' => ['35ft Fresh Flower Wall', 'Handcrafted Gold Throne', 'Crystal Chandelier Clusters', 'Red Carpet Aisle'],
                'items' => [
                    ['name' => '35x14ft Fresh Orchid & Rose Panoramic Wall', 'quantity' => 1],
                    ['name' => 'Handcrafted Sovereign Maharaja Throne Pair', 'quantity' => 1],
                    ['name' => 'Crystal Chandelier Trio Cluster', 'quantity' => 1],
                    ['name' => 'High-Lumen Warm Par Lighting Grid', 'quantity' => 16],
                ],
                'display_order' => 30,
            ],
            [
                'category_slug' => 'reception',
                'name' => 'Royal Reception Stage Decor',
                'slug' => 'royal-reception-stage-decor',
                'tagline' => 'Sophisticated champagne & gold floral architecture with luxury couch',
                'short_description' => 'A stately reception stage with champagne drapes, golden chandeliers, and fresh floral pillars.',
                'description' => 'Combines modern sophistication with timeless North Indian royal tradition. Ideal for banquet halls and large wedding lawns.',
                'primary_image' => 'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1000&q=80',
                'location' => 'Gopalganj',
                'starting_price' => 110000,
                'base_price' => 110000.00,
                'discount_price' => 98000.00,
                'style' => 'Royal',
                'primary_color' => 'Cream & Gold',
                'color_theme' => 'Champagne, Cream & Warm Gold',
                'guest_capacity' => '500-1000 Guests',
                'setup_time' => '6-8 Hours',
                'rating' => 4.9,
                'reviews_count' => 20,
                'is_featured' => false,
                'is_trending' => true,
                'is_available' => true,
                'is_active' => true,
                'features' => ['Champagne Silk Drapery', 'Golden Arch Frames', 'Plush Curved Sofa', 'Ambient Spotlights'],
                'items' => [
                    ['name' => 'Champagne Silk Pleated Backdrop with Floral Header', 'quantity' => 1],
                    ['name' => 'Curved Gold-Rimmed Upholstered Sofa', 'quantity' => 1],
                    ['name' => 'Warm Follow-Spot and Par System', 'quantity' => 8],
                ],
                'display_order' => 31,
            ],
        ];

        foreach ($decorationsData as $item) {
            $cat = $categoryModels[$item['category_slug']] ?? null;
            if ($cat) {
                $dec = Decoration::updateOrCreate(
                    ['slug' => $item['slug']],
                    [
                        'category_id' => $cat->id,
                        'name' => $item['name'],
                        'slug' => $item['slug'],
                        'tagline' => $item['tagline'],
                        'short_description' => $item['short_description'] ?? $item['tagline'],
                        'description' => $item['description'],
                        'primary_image' => $item['primary_image'],
                        'location' => $item['location'],
                        'starting_price' => $item['starting_price'],
                        'base_price' => $item['base_price'],
                        'discount_price' => $item['discount_price'],
                        'price_unit' => 'starting from',
                        'style' => $item['style'],
                        'primary_color' => $item['primary_color'],
                        'color_theme' => $item['color_theme'],
                        'guest_capacity' => $item['guest_capacity'],
                        'setup_time' => $item['setup_time'],
                        'rating' => $item['rating'],
                        'reviews_count' => $item['reviews_count'],
                        'is_featured' => $item['is_featured'],
                        'is_trending' => $item['is_trending'],
                        'is_available' => $item['is_available'],
                        'is_active' => $item['is_active'],
                        'features' => $item['features'],
                        'display_order' => $item['display_order'],
                    ]
                );

                // Add decoration images
                DecorationImage::updateOrCreate(
                    ['decoration_id' => $dec->id, 'image_url' => $item['primary_image']],
                    [
                        'caption' => $item['name'] . ' Main View',
                        'alt_text' => 'Traditional Bihar ' . $item['name'] . ' setup in ' . $item['location'],
                        'is_primary' => true,
                        'display_order' => 1
                    ]
                );

                // Add secondary showcase images
                DecorationImage::updateOrCreate(
                    ['decoration_id' => $dec->id, 'image_url' => 'https://images.unsplash.com/photo-1583939411023-14783179e581?auto=format&fit=crop&w=1000&q=80'],
                    [
                        'caption' => $item['name'] . ' Floral Detailing & Seating',
                        'alt_text' => 'Floral detailing for ' . $item['name'],
                        'is_primary' => false,
                        'display_order' => 2
                    ]
                );

                DecorationImage::updateOrCreate(
                    ['decoration_id' => $dec->id, 'image_url' => 'https://images.unsplash.com/photo-1544078751-58fee2d8a03b?auto=format&fit=crop&w=1000&q=80'],
                    [
                        'caption' => $item['name'] . ' Night Lighting & Ambience',
                        'alt_text' => 'Night lighting view for ' . $item['name'],
                        'is_primary' => false,
                        'display_order' => 3
                    ]
                );

                // Seed decoration items (What's Included)
                if (!empty($item['items'])) {
                    // Clear and re-insert items
                    DecorationItem::where('decoration_id', $dec->id)->delete();
                    foreach ($item['items'] as $it) {
                        DecorationItem::create([
                            'decoration_id' => $dec->id,
                            'name' => $it['name'],
                            'description' => 'Included in base setup with complete professional installation and dismantling.',
                            'quantity' => $it['quantity'] ?? 1,
                        ]);
                    }
                }

                // Attach sample add-ons
                $randomAddons = array_slice($addonModels, 0, rand(3, 5));
                $addonIds = array_map(fn($a) => $a->id, $randomAddons);
                $dec->addons()->sync($addonIds);
            }
        }

        // 5. Packages
        $packagesData = [
            [
                'name' => 'Shubh Vivah Package',
                'slug' => 'shubh-vivah-package',
                'badge' => 'Most Popular',
                'tagline' => 'Comprehensive 4-Ceremony Wedding Decoration',
                'description' => 'Our flagship package covering all essential rituals with signature Bihar styling and dedicated decor supervisor throughout.',
                'included_ceremonies' => ['Haldi Ceremony', 'Mehendi Setup', 'Vedic Wedding Mandap', 'Grand Reception Stage'],
                'highlights' => [
                    'Traditional Marigold Haldi Urli setup',
                    'Vibrant colorful Mehendi lounge with seating',
                    'Vedic 4-Pillar fresh flower Mandap with Havan area',
                    'Grand Reception stage with royal sofa & lighting',
                    'Complimentary Floral Welcome Gate',
                    'Dedicated on-site decor team throughout all events',
                ],
                'starting_price' => 240000,
                'image_url' => 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=900&q=80',
                'is_featured' => true,
                'display_order' => 1,
            ],
            [
                'name' => 'Traditional Bihar Wedding Package',
                'slug' => 'traditional-bihar-wedding-package',
                'badge' => 'Heritage Classic',
                'tagline' => 'Jaimala, Mandap, Baraat Swagat & Reception',
                'description' => 'Focused on the sacred main day celebrations with traditional floral grandeur, brass accents, and auspicious motifs.',
                'included_ceremonies' => ['Baraat Entry Swagat', 'Grand Jaimala Stage', 'Vedic Wedding Mandap', 'Reception Stage'],
                'highlights' => [
                    'Grand Baraat Swagat Gateway with lighting',
                    'Traditional Red & Gold Jaimala Stage with throne',
                    'Authentic 4-Pillar fresh floral Mandap',
                    'Reception backdrop with warm spotlights',
                    'Red carpet runway for Varmala procession',
                    'Complete lighting setup for main lawns/hall',
                ],
                'starting_price' => 210000,
                'image_url' => 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=900&q=80',
                'is_featured' => true,
                'display_order' => 2,
            ],
            [
                'name' => 'Complete Wedding Celebration',
                'slug' => 'complete-wedding-celebration',
                'badge' => 'All-Inclusive Grand',
                'tagline' => 'End-to-End 5-Event Luxury Decoration',
                'description' => 'The ultimate worry-free celebration package covering every ritual from pre-wedding festivities to the grand reception.',
                'included_ceremonies' => ['Haldi', 'Mehendi', 'Sangeet Night', 'Vedic Vivah', 'Grand Reception'],
                'highlights' => [
                    'Custom theme designs for all 5 ceremonies',
                    'Live acoustic & dance stage for Sangeet night',
                    'Grand floral archway with cold pyros for entry',
                    'Premium fresh Dutch roses & Rajnigandha florals',
                    'VIP family lounge seating arrangements',
                    'Senior event decor manager & round-the-clock support',
                ],
                'starting_price' => 325000,
                'image_url' => 'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=900&q=80',
                'is_featured' => true,
                'display_order' => 3,
            ],
        ];

        foreach ($packagesData as $pkg) {
            Package::updateOrCreate(['slug' => $pkg['slug']], $pkg);
        }

        // 6. Service Areas (Accurately separated: Bihar vs Nearby UP)
        $serviceAreasData = [
            ['name' => 'Siwan', 'state' => 'Bihar', 'district' => 'Siwan', 'category' => 'Bihar Core', 'status_note' => 'Primary Base & Full Team', 'is_primary' => true, 'display_order' => 1],
            ['name' => 'Mairwa', 'state' => 'Bihar', 'district' => 'Siwan', 'category' => 'Bihar Core', 'status_note' => 'Full Team Available', 'is_primary' => true, 'display_order' => 2],
            ['name' => 'Gopalganj', 'state' => 'Bihar', 'district' => 'Gopalganj', 'category' => 'Bihar Core', 'status_note' => 'Active Daily Coverage', 'is_primary' => true, 'display_order' => 3],
            ['name' => 'Chapra / Saran', 'state' => 'Bihar', 'district' => 'Saran', 'category' => 'Bihar Core', 'status_note' => 'Active Daily Coverage', 'is_primary' => true, 'display_order' => 4],
            ['name' => 'Barharia', 'state' => 'Bihar', 'district' => 'Siwan', 'category' => 'Bihar Core', 'status_note' => 'Local Service Team', 'is_primary' => false, 'display_order' => 5],
            ['name' => 'Maharajganj', 'state' => 'Bihar', 'district' => 'Siwan', 'category' => 'Bihar Core', 'status_note' => 'Local Service Team', 'is_primary' => false, 'display_order' => 6],
            ['name' => 'Raghunathpur', 'state' => 'Bihar', 'district' => 'Siwan', 'category' => 'Bihar Extended', 'status_note' => 'Full Team Available', 'is_primary' => false, 'display_order' => 7],
            ['name' => 'Ziradei', 'state' => 'Bihar', 'district' => 'Siwan', 'category' => 'Bihar Extended', 'status_note' => 'Full Team Available', 'is_primary' => false, 'display_order' => 8],
            ['name' => 'Darauli', 'state' => 'Bihar', 'district' => 'Siwan', 'category' => 'Bihar Extended', 'status_note' => 'Full Team Available', 'is_primary' => false, 'display_order' => 9],
            ['name' => 'Andar', 'state' => 'Bihar', 'district' => 'Siwan', 'category' => 'Bihar Extended', 'status_note' => 'Full Team Available', 'is_primary' => false, 'display_order' => 10],
            ['name' => 'Hasanpura', 'state' => 'Bihar', 'district' => 'Siwan', 'category' => 'Bihar Extended', 'status_note' => 'Full Team Available', 'is_primary' => false, 'display_order' => 11],
            ['name' => 'Lakri Nabiganj', 'state' => 'Bihar', 'district' => 'Siwan', 'category' => 'Bihar Extended', 'status_note' => 'Full Team Available', 'is_primary' => false, 'display_order' => 12],
            // Nearby Uttar Pradesh
            ['name' => 'Gorakhpur', 'state' => 'Uttar Pradesh', 'district' => 'Gorakhpur', 'category' => 'Nearby Uttar Pradesh', 'status_note' => 'Selected Advance Bookings', 'is_primary' => false, 'display_order' => 13],
            ['name' => 'Deoria', 'state' => 'Uttar Pradesh', 'district' => 'Deoria', 'category' => 'Nearby Uttar Pradesh', 'status_note' => 'Selected Advance Bookings', 'is_primary' => false, 'display_order' => 14],
            ['name' => 'Bhatpar Rani', 'state' => 'Uttar Pradesh', 'district' => 'Deoria', 'category' => 'Nearby Uttar Pradesh', 'status_note' => 'Border Area Bookings', 'is_primary' => false, 'display_order' => 15],
            ['name' => 'Salempur', 'state' => 'Uttar Pradesh', 'district' => 'Deoria', 'category' => 'Nearby Uttar Pradesh', 'status_note' => 'Border Area Bookings', 'is_primary' => false, 'display_order' => 16],
        ];

        foreach ($serviceAreasData as $area) {
            ServiceArea::updateOrCreate(['name' => $area['name']], $area);
        }

        // 7. Reviews
        $reviewsData = [
            [
                'customer_name' => 'Ramesh Chandra Pandey',
                'city' => 'Siwan, Bihar',
                'event_type' => 'Jaimala Ceremony',
                'rating' => 5,
                'review_text' => 'Beautiful Jaimala decoration and very cooperative team. The stage looked exactly the way we wanted for our daughter\'s wedding in Siwan. The fresh red roses and lighting were praised by all our guests.',
                'avatar_initials' => 'RP',
                'event_date_formatted' => 'November 2024',
                'is_featured' => true,
                'display_order' => 1,
            ],
            [
                'customer_name' => 'Amit Kumar Singh',
                'city' => 'Gopalganj, Bihar',
                'event_type' => 'Haldi & Mehendi Celebration',
                'rating' => 5,
                'review_text' => 'The Marigold Haldi setup was so vibrant and fresh! Aditya Utsav arrived on time, completed the setup 3 hours before the ritual started, and handled everything with genuine professionalism.',
                'avatar_initials' => 'AS',
                'event_date_formatted' => 'December 2024',
                'is_featured' => true,
                'display_order' => 2,
            ],
            [
                'customer_name' => 'Rajeshwar Mishra',
                'city' => 'Chapra, Bihar',
                'event_type' => 'Mandap & Reception Stage',
                'rating' => 5,
                'review_text' => 'Aditya Utsav managed our Mandap and Reception stage in Chapra with exceptional punctuality. Traditional Vedic touch combined with clean finishing made the ceremony memorable for our family.',
                'avatar_initials' => 'RM',
                'event_date_formatted' => 'January 2025',
                'is_featured' => true,
                'display_order' => 3,
            ],
            [
                'customer_name' => 'Alok Kumar Verma',
                'city' => 'Mairwa, Bihar',
                'event_type' => 'Traditional Vivah Mandap',
                'rating' => 5,
                'review_text' => 'Their team was punctual and respectful of all traditional rituals during the Vivah ceremony. Transparent pricing and no hidden costs. Truly the most reliable wedding decor in Siwan region.',
                'avatar_initials' => 'AV',
                'event_date_formatted' => 'February 2025',
                'is_featured' => true,
                'display_order' => 4,
            ],
        ];

        foreach ($reviewsData as $rev) {
            Review::updateOrCreate(['customer_name' => $rev['customer_name']], $rev);
        }

        // 8. Gallery Items
        $galleryData = [
            [
                'title' => 'Traditional Bihar Jaimala Stage',
                'category' => 'Jaimala',
                'image_url' => 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=900&q=80',
                'location' => 'Siwan, Bihar',
                'caption' => 'Royal burgundy and gold floral stage setup',
                'is_featured' => true,
                'display_order' => 1,
            ],
            [
                'title' => 'Vedic 4-Pillar Mandap Setup',
                'category' => 'Mandap',
                'image_url' => 'https://images.unsplash.com/photo-1583939003579-730e3918a45a?auto=format&fit=crop&w=900&q=80',
                'location' => 'Siwan, Bihar',
                'caption' => 'Sacred vivah havan and floral canopy',
                'is_featured' => true,
                'display_order' => 2,
            ],
            [
                'title' => 'Marigold Urli Haldi Setup',
                'category' => 'Haldi',
                'image_url' => 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=900&q=80',
                'location' => 'Mairwa, Bihar',
                'caption' => 'Bright yellow marigold floral curtains',
                'is_featured' => true,
                'display_order' => 3,
            ],
            [
                'title' => 'Festive Courtyard Mehendi',
                'category' => 'Mehendi',
                'image_url' => 'https://images.unsplash.com/photo-1604014237800-1c9102c219da?auto=format&fit=crop&w=900&q=80',
                'location' => 'Gopalganj, Bihar',
                'caption' => 'Colorful diwan seating with floral jhula',
                'is_featured' => true,
                'display_order' => 4,
            ],
            [
                'title' => 'High-Energy Sangeet Lighting Stage',
                'category' => 'Sangeet',
                'image_url' => 'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=900&q=80',
                'location' => 'Siwan, Bihar',
                'caption' => 'Warm ambient par lighting and family stage',
                'is_featured' => true,
                'display_order' => 5,
            ],
            [
                'title' => 'Grand Evening Reception Stage',
                'category' => 'Reception',
                'image_url' => 'https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=900&q=80',
                'location' => 'Chapra, Bihar',
                'caption' => '30ft wide floral wall with gold crown seating',
                'is_featured' => true,
                'display_order' => 6,
            ],
            [
                'title' => 'Royal Swagat Baraat Gate',
                'category' => 'Baraat',
                'image_url' => 'https://images.unsplash.com/photo-1532712938310-34cb3982ef74?auto=format&fit=crop&w=900&q=80',
                'location' => 'Siwan, Bihar',
                'caption' => 'Grand floral gateway with hanging brass diyas',
                'is_featured' => true,
                'display_order' => 7,
            ],
            [
                'title' => 'Auspicious Floral Toran Entrance',
                'category' => 'Entrance',
                'image_url' => 'https://images.unsplash.com/photo-1545232979-fbf6759c2560?auto=format&fit=crop&w=900&q=80',
                'location' => 'Siwan, Bihar',
                'caption' => 'Fresh marigold & mango leaf toran entrance',
                'is_featured' => true,
                'display_order' => 8,
            ],
        ];

        foreach ($galleryData as $gItem) {
            GalleryItem::updateOrCreate(['title' => $gItem['title']], $gItem);
        }

        // 9. Offers
        Offer::updateOrCreate(
            ['title' => 'Wedding Season Special'],
            [
                'subtitle' => 'Plan Your Bihar Wedding With Aditya Utsav',
                'description' => 'Book your full Vivah package early and receive a complimentary Grand Floral Welcome Gate and traditional Brass Lamp entryway setup for your main wedding day.',
                'highlight_badge' => 'Limited Dates Available',
                'discount_text' => 'Complimentary Grand Floral Swagat Gate with Full Packages',
                'valid_till' => 'Upcoming Lagan Season',
                'cta_text' => 'Get a Custom Quote',
                'cta_link' => '/quote',
                'image_url' => 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=80',
                'is_active' => true,
            ]
        );

        // 10. FAQs
        $faqsData = [
            [
                'question' => 'How early should we book our wedding decoration date?',
                'answer' => 'Due to peak wedding (Lagan) dates in Bihar, dates book up quickly. We recommend reserving your date at least 4 to 8 weeks in advance to secure your preferred floral and stage designs.',
                'category' => 'Booking & Setup',
                'is_featured' => true,
                'display_order' => 1,
            ],
            [
                'question' => 'Which cities and districts do you serve?',
                'answer' => 'Our primary hub is Siwan, Bihar. We actively serve all areas across Siwan (Mairwa, Barharia, Maharajganj, Ziradei, Darauli, Andar, Hasanpura), Gopalganj, and Saran/Chapra. We also take advance selected bookings in bordering Uttar Pradesh locations like Deoria and Gorakhpur.',
                'category' => 'Service Areas',
                'is_featured' => true,
                'display_order' => 2,
            ],
            [
                'question' => 'Do you use fresh flowers for Jaimala stages and Mandap?',
                'answer' => 'Yes! We specialize in premium fresh flowers including fresh red & pink roses, fragrant Rajnigandha (tuberoses), fresh local marigolds (Genda phool), and orchids, combined with high-grade silk accents for durable, long-lasting beauty through the entire night.',
                'category' => 'Decoration Details',
                'is_featured' => true,
                'display_order' => 3,
            ],
            [
                'question' => 'Can decorations be customized to our family traditions and venue size?',
                'answer' => 'Absolutely. Every family has unique ceremonial needs. Whether your venue is a private family courtyard, a community lawn, or a marriage palace, we customize dimensions, colors, and ritual arrangements (like Havan Kund & Tilak chauki) accordingly.',
                'category' => 'Customization',
                'is_featured' => true,
                'display_order' => 4,
            ],
            [
                'question' => 'What is the setup timeline on the wedding day?',
                'answer' => 'Our decoration team arrives well in advance. For evening Jaimala and Vivah ceremonies, our team completes 100% of the stage, lighting, and seating setup at least 2 to 3 hours before the guests and Baraat arrive.',
                'category' => 'Booking & Setup',
                'is_featured' => true,
                'display_order' => 5,
            ],
            [
                'question' => 'How can we check date availability and get a quote?',
                'answer' => 'You can use the availability checker on our homepage, call our Siwan office directly, or submit a request on our "Get a Quote" page. We will contact you with clear, transparent pricing and design options.',
                'category' => 'General',
                'is_featured' => true,
                'display_order' => 6,
            ],
        ];

        foreach ($faqsData as $faq) {
            Faq::updateOrCreate(['question' => $faq['question']], $faq);
        }
    }
}
